### ISSUE TITLE
Gofile error

### ISSUE THREAD

**Issue by satyamverma43** [AbirHasan2005/Cloud-UPManager-Bot#4]
Gofile.io is not Upload file its show admin code error please fix it

**Comment by AbirHasan2005** [comment]
Send Error Logs Please!

**Comment by satyamverma43** [comment]
@Cloud_UPManager_Bot when i use this demo bot then gofile does not upload file show error in 'admin 
![Screenshot_2021-06-07-12-33-43-25_74594bd74a0419242537a8d02ba17993](https://user-images.githubusercontent.com/69762426/120973543-b4f16580-c78c-11eb-9765-962a9afb44f8.jpg)
code'

**Comment by AbirHasan2005** [comment]
Can you show what you put inline?

**Comment by satyamverma43** [comment]
Okk bro . 🤗

**Comment by AbirHasan2005** [comment]
Fixed Now!
